<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Spp;
use App\Models\User;
use App\Models\Kelas;
use App\Models\Siswa;
use App\Models\Pembayaran;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        $petugas = [
            [
                'username' => 'admin',
                'password' => bcrypt('adminadmin'),
                'nama_petugas' => 'Bintang',
                'level' => 'admin'
            ],
            [
                'username' => 'petugas',
                'password' => bcrypt('petugaspetugas'),
                'nama_petugas' => 'Zhaka',
                'level' => 'petugas'
            ],
];

$siswass = [
    [
        'X RPL 1' => [
            [
                'nama' => 'Ahmad Ramadhan',
                'nis' => '222-001',
                'alamat' => 'jl pajayang',
                'nisn' => '67972916',
                'id_kelas' => 1,
                'id_spp' => 1,
                'no_telp' => '8907674536753',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Alfathino Ramadhan',
                'nis' => '222-002',
                'alamat' => 'jl goaria',
                'nisn' => '65971049',
                'id_kelas' => 1,
                'id_spp' => 1,
                'no_telp' => '8907674536777',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Alifiah Ramadhani',
                'nis' => '222-003',
                'alamat' => 'jl dg rammang',
                'nisn' => '63284508',
                'id_kelas' => 1,
                'id_spp' => 1,
                'no_telp' => '8907674536799',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Anam Surya Dafi',
                'nis' => '222-004',
                'alamat' => 'jl printis km 08',
                'nisn' => '78729522',
                'id_kelas' => 1,
                'id_spp' => 1,
                'no_telp' => '8907674536657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Andi Imran Pratama',
                'nis' => '222-005',
                'alamat' => 'jl mamuju',
                'nisn' => '78655594',
                'id_kelas' => 1,
                'id_spp' => 1,
                'no_telp' => '8907884536657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Nadila Nur Azizah',
                'nis' => '222-006',
                'alamat' => 'btn kondam',
                'nisn' => '63583686',
                'id_kelas' => 1,
                'id_spp' => 1,
                'no_telp' => '8907884536657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Nilang Cahya',
                'nis' => '222-007',
                'alamat' => 'jl pettarani',
                'nisn' => '63583996',
                'id_kelas' => 1,
                'id_spp' => 1,
                'no_telp' => '8909884536657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Nur Afni Aprilia',
                'nis' => '222-008',
                'alamat' => 'jl sudiang raya',
                'nisn' => '63583933',
                'id_kelas' => 1,
                'id_spp' => 1,
                'no_telp' => '8900884536657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Nur Bungasari .J',
                'nis' => '222-009',
                'alamat' => 'jl manikoaya',
                'nisn' => '63583972',
                'id_kelas' => 1,
                'id_spp' => 1,
                'no_telp' => '8907884588657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Nurhikmah',
                'nis' => '222-010',
                'alamat' => 'bps 1 blk f8 no 19',
                'nisn' => '635839444',
                'id_kelas' => 1,
                'id_spp' => 1,
                'no_telp' => '89078847776657',
                'jenis_kelamin' => 'p',
            ],
        ],
        'X RPL 2' => [
            [
                'nama' => 'Ahmad Imam Fahresi',
                'nis' => '222-011',
                'alamat' => 'jl vetran',
                'nisn' => '62196092',
                'id_kelas' => 2,
                'id_spp' => 1,
                'no_telp' => '6219609236753',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Ahmad Zahid Syarifuddin',
                'nis' => '222-012',
                'alamat' => 'jl pajayang',
                'nisn' => '65878126',
                'id_kelas' => 2,
                'id_spp' => 1,
                'no_telp' => '6587812636777',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Alfiano Egot',
                'nis' => '222-013',
                'alamat' => 'jl pajayang',
                'nisn' => '69185749',
                'id_kelas' => 2,
                'id_spp' => 1,
                'no_telp' => '6918574936799',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Andi Fachrie Rachman',
                'nis' => '222-014',
                'alamat' => 'jl poros maros-makassar',
                'nisn' => '73629205',
                'id_kelas' => 2,
                'id_spp' => 1,
                'no_telp' => '7362920536657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Andi Nurul Uswa Baso',
                'nis' => '222-015',
                'alamat' => 'jl pajayang',
                'nisn' => '79525234',
                'id_kelas' => 2,
                'id_spp' => 1,
                'no_telp' => '7952523436657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Azmi Nur Syaifa',
                'nis' => '222-016',
                'alamat' => 'btn kodam',
                'nisn' => '73620416',
                'id_kelas' => 2,
                'id_spp' => 1,
                'no_telp' => '7362041636657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Fifi Muliani',
                'nis' => '222-017',
                'alamat' => 'btn kodam',
                'nisn' => '61859811',
                'id_kelas' => 2,
                'id_spp' => 1,
                'no_telp' => '6185981136657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Firmansyah',
                'nis' => '222-018',
                'alamat' => 'jl sudiang raya',
                'nisn' => '58288836',
                'id_kelas' => 2,
                'id_spp' => 1,
                'no_telp' => '5828883636657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Ikmal Khair Wirawan',
                'nis' => '222-019',
                'alamat' => 'jl mamuju',
                'nisn' => '68281324',
                'id_kelas' => 2,
                'id_spp' => 1,
                'no_telp' => '6828132488657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Isra',
                'nis' => '222-020',
                'alamat' => 'jl mamuju',
                'nisn' => '72733751',
                'id_kelas' => 2,
                'id_spp' => 1,
                'no_telp' => '72733751776657',
                'jenis_kelamin' => 'l',
            ],
        ],
        'X TKJ 1' => [
            [
                'nama' => 'Agus Andhani Purwadi',
                'nis' => '222-021',
                'alamat' => 'jl vetran',
                'nisn' => '61278781',
                'id_kelas' => 3,
                'id_spp' => 1,
                'no_telp' => '6127878136753',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Airin Putri Wulandari',
                'nis' => '222-022',
                'alamat' => 'jl pajayang',
                'nisn' => '73126837',
                'id_kelas' => 3,
                'id_spp' => 1,
                'no_telp' => '7312683736777',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Amirul Ihsan',
                'nis' => '222-023',
                'alamat' => 'jl pajayang',
                'nisn' => '76141281',
                'id_kelas' => 3,
                'id_spp' => 1,
                'no_telp' => '7614128136799',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Andi Rexa Destalia',
                'nis' => '222-024',
                'alamat' => 'jl poros maros-makassar',
                'nisn' => '68321194',
                'id_kelas' => 3,
                'id_spp' => 1,
                'no_telp' => '6832119436657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Arya Saputra',
                'nis' => '222-025',
                'alamat' => 'jl pajayang',
                'nisn' => '67301799',
                'id_kelas' => 3,
                'id_spp' => 1,
                'no_telp' => '6730179936657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Azizah Putri Nurmaidah',
                'nis' => '222-026',
                'alamat' => 'btn kodam',
                'nisn' => '74815617',
                'id_kelas' => 3,
                'id_spp' => 1,
                'no_telp' => '7481561736657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Bayu Nurhuda',
                'nis' => '222-027',
                'alamat' => 'btn kodam',
                'nisn' => '3068020284',
                'id_kelas' => 3,
                'id_spp' => 1,
                'no_telp' => '3068020284366',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Boney Marshel Latupeirissa',
                'nis' => '222-028',
                'alamat' => 'jl sudiang raya',
                'nisn' => '73264652',
                'id_kelas' => 3,
                'id_spp' => 1,
                'no_telp' => '7326465236657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Elsa Sulian',
                'nis' => '222-029',
                'alamat' => 'jl mamuju',
                'nisn' => '68993275',
                'id_kelas' => 3,
                'id_spp' => 1,
                'no_telp' => '6899327588657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Khairun Nisa',
                'nis' => '222-030',
                'alamat' => 'jl mamuju',
                'nisn' => '79700723',
                'id_kelas' => 3,
                'id_spp' => 1,
                'no_telp' => '79700723776657',
                'jenis_kelamin' => 'p',
            ],
        ],
        'X MMK 1' => [
            [
                'nama' => 'Abil Ardhaya Simanungkalit',
                'nis' => '222-031',
                'alamat' => 'jl vetran',
                'nisn' => '65706099',
                'id_kelas' => 4,
                'id_spp' => 1,
                'no_telp' => '6570608736753',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Abraham Scott Tangguh Bida',
                'nis' => '222-032',
                'alamat' => 'jl pajayang',
                'nisn' => '67561041',
                'id_kelas' => 4,
                'id_spp' => 1,
                'no_telp' => '6756184136777',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Achtor Teratai Sebatanan',
                'nis' => '222-033',
                'alamat' => 'jl pajayang',
                'nisn' => '63223092',
                'id_kelas' => 4,
                'id_spp' => 1,
                'no_telp' => '6322709236799',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Aldiksa Ilyas Agustian',
                'nis' => '222-034',
                'alamat' => 'jl poros maros-makassar',
                'nisn' => '71693322',
                'id_kelas' => 4,
                'id_spp' => 1,
                'no_telp' => '7169337736657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Andi Ghefira Dwi Azahra',
                'nis' => '222-035',
                'alamat' => 'jl pajayang',
                'nisn' => '61707503',
                'id_kelas' => 4,
                'id_spp' => 1,
                'no_telp' => '6177755336657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Ayu Wardana',
                'nis' => '222-036',
                'alamat' => 'btn kodam',
                'nisn' => '65119033',
                'id_kelas' => 4,
                'id_spp' => 1,
                'no_telp' => '6511923336657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Chelsea Fatima Al-Zahra Panjaitan',
                'nis' => '222-037',
                'alamat' => 'btn kodam',
                'nisn' => '66240936',
                'id_kelas' => 4,
                'id_spp' => 1,
                'no_telp' => '66242936366',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Dewi Wulandari Zainuddin',
                'nis' => '222-038',
                'alamat' => 'jl sudiang raya',
                'nisn' => '65207071',
                'id_kelas' => 4,
                'id_spp' => 1,
                'no_telp' => '6520727136657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Diszhar Aysar Hasnur',
                'nis' => '222-039',
                'alamat' => 'jl mamuju',
                'nisn' => '79850061',
                'id_kelas' => 4,
                'id_spp' => 1,
                'no_telp' => '7985636188657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Dwi Puspita Sari',
                'nis' => '222-040',
                'alamat' => 'jl mamuju',
                'nisn' => '73007341',
                'id_kelas' => 4,
                'id_spp' => 1,
                'no_telp' => '73397341776657',
                'jenis_kelamin' => 'p',
            ],
        ],
        'XI RPL 1' => [
            [
                'nama' => 'Ahmad Ramadhan',
                'nis' => '333-001',
                'alamat' => 'jl pajayang',
                'nisn' => '67911916',
                'id_kelas' => 5,
                'id_spp' => 2,
                'no_telp' => '8907674536753',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Alfathino Ramadhan',
                'nis' => '333-002',
                'alamat' => 'jl goaria',
                'nisn' => '65922049',
                'id_kelas' => 5,
                'id_spp' => 2,
                'no_telp' => '8907674536777',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Alifiah Ramadhani',
                'nis' => '333-003',
                'alamat' => 'jl dg rammang',
                'nisn' => '63233508',
                'id_kelas' => 5,
                'id_spp' => 2,
                'no_telp' => '8907674536799',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Anam Surya Dafi',
                'nis' => '333-004',
                'alamat' => 'jl printis km 08',
                'nisn' => '78724422',
                'id_kelas' => 5,
                'id_spp' => 2,
                'no_telp' => '8907674536657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Andi Imran Pratama',
                'nis' => '333-005',
                'alamat' => 'jl mamuju',
                'nisn' => '78699594',
                'id_kelas' => 5,
                'id_spp' => 2,
                'no_telp' => '8907884536657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Nadila Nur Azizah',
                'nis' => '333-006',
                'alamat' => 'btn kondam',
                'nisn' => '63566686',
                'id_kelas' => 5,
                'id_spp' => 2,
                'no_telp' => '8907884536657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Nilang Cahya',
                'nis' => '333-007',
                'alamat' => 'jl pettarani',
                'nisn' => '63577996',
                'id_kelas' => 5,
                'id_spp' => 2,
                'no_telp' => '8909884536657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Nur Afni Aprilia',
                'nis' => '333-008',
                'alamat' => 'jl sudiang raya',
                'nisn' => '63580033',
                'id_kelas' => 5,
                'id_spp' => 2,
                'no_telp' => '8900884536657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Nur Bungasari .J',
                'nis' => '333-009',
                'alamat' => 'jl manikoaya',
                'nisn' => '63544972',
                'id_kelas' => 5,
                'id_spp' => 2,
                'no_telp' => '8907884588657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Nurhikmah',
                'nis' => '333-010',
                'alamat' => 'bps 1 blk f8 no 19',
                'nisn' => '635539444',
                'id_kelas' => 5,
                'id_spp' => 2,
                'no_telp' => '89078847776657',
                'jenis_kelamin' => 'p',
            ],
        ],
        'XI RPL 2' => [
            [
                'nama' => 'Ahmad Imam Fahresi',
                'nis' => '333-011',
                'alamat' => 'jl vetran',
                'nisn' => '62167092',
                'id_kelas' => 6,
                'id_spp' => 2,
                'no_telp' => '6219609236753',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Ahmad Zahid Syarifuddin',
                'nis' => '333-012',
                'alamat' => 'jl pajayang',
                'nisn' => '65800126',
                'id_kelas' => 6,
                'id_spp' => 2,
                'no_telp' => '6587812636777',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Alfiano Egot',
                'nis' => '333-013',
                'alamat' => 'jl pajayang',
                'nisn' => '69189749',
                'id_kelas' => 6,
                'id_spp' => 2,
                'no_telp' => '6918574936799',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Andi Fachrie Rachman',
                'nis' => '333-014',
                'alamat' => 'jl poros maros-makassar',
                'nisn' => '73678205',
                'id_kelas' => 6,
                'id_spp' => 2,
                'no_telp' => '7362920536657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Andi Nurul Uswa Baso',
                'nis' => '333-015',
                'alamat' => 'jl pajayang',
                'nisn' => '79555234',
                'id_kelas' => 6,
                'id_spp' => 2,
                'no_telp' => '7952523436657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Azmi Nur Syaifa',
                'nis' => '333-016',
                'alamat' => 'btn kodam',
                'nisn' => '73676416',
                'id_kelas' => 6,
                'id_spp' => 2,
                'no_telp' => '7362041636657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Fifi Muliani',
                'nis' => '333-017',
                'alamat' => 'btn kodam',
                'nisn' => '61854811',
                'id_kelas' => 6,
                'id_spp' => 2,
                'no_telp' => '6185981136657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Firmansyah',
                'nis' => '333-018',
                'alamat' => 'jl sudiang raya',
                'nisn' => '58242836',
                'id_kelas' => 6,
                'id_spp' => 2,
                'no_telp' => '5828883636657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Ikmal Khair Wirawan',
                'nis' => '333-019',
                'alamat' => 'jl mamuju',
                'nisn' => '68290324',
                'id_kelas' => 6,
                'id_spp' => 2,
                'no_telp' => '6828132488657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Isra',
                'nis' => '333-020',
                'alamat' => 'jl mamuju',
                'nisn' => '72766751',
                'id_kelas' => 6,
                'id_spp' => 2,
                'no_telp' => '72733751776657',
                'jenis_kelamin' => 'l',
            ],
        ],
        'XI TKJ 1' => [
            [
                'nama' => 'Agus Andhani Purwadi',
                'nis' => '333-021',
                'alamat' => 'jl vetran',
                'nisn' => '6156881',
                'id_kelas' => 7,
                'id_spp' => 2,
                'no_telp' => '6127878765753',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Airin Putri Wulandari',
                'nis' => '333-022',
                'alamat' => 'jl pajayang',
                'nisn' => '7356687',
                'id_kelas' => 7,
                'id_spp' => 2,
                'no_telp' => '7312683765777',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Amirul Ihsan',
                'nis' => '333-023',
                'alamat' => 'jl pajayang',
                'nisn' => '7656181',
                'id_kelas' => 7,
                'id_spp' => 2,
                'no_telp' => '7614128765799',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Andi Rexa Destalia',
                'nis' => '333-024',
                'alamat' => 'jl poros maros-makassar',
                'nisn' => '6856184',
                'id_kelas' => 7,
                'id_spp' => 2,
                'no_telp' => '6832119765657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Arya Saputra',
                'nis' => '333-025',
                'alamat' => 'jl pajayang',
                'nisn' => '6756189',
                'id_kelas' => 7,
                'id_spp' => 2,
                'no_telp' => '6730179765657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Azizah Putri Nurmaidah',
                'nis' => '333-026',
                'alamat' => 'btn kodam',
                'nisn' => '7456587',
                'id_kelas' => 7,
                'id_spp' => 2,
                'no_telp' => '7481561765657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Bayu Nurhuda',
                'nis' => '333-027',
                'alamat' => 'btn kodam',
                'nisn' => '305608284',
                'id_kelas' => 7,
                'id_spp' => 2,
                'no_telp' => '3068020765366',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Boney Marshel Latupeirissa',
                'nis' => '333-028',
                'alamat' => 'jl sudiang raya',
                'nisn' => '7356482',
                'id_kelas' => 7,
                'id_spp' => 2,
                'no_telp' => '7326465765657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Elsa Sulian',
                'nis' => '333-029',
                'alamat' => 'jl mamuju',
                'nisn' => '6856385',
                'id_kelas' => 7,
                'id_spp' => 2,
                'no_telp' => '6899327765657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Khairun Nisa',
                'nis' => '333-030',
                'alamat' => 'jl mamuju',
                'nisn' => '7956083',
                'id_kelas' => 7,
                'id_spp' => 2,
                'no_telp' => '79700727656657',
                'jenis_kelamin' => 'p',
            ],
        ],
        'XI MMK 1' => [
            [
                'nama' => 'Abil Ardhaya Simanungkalit',
                'nis' => '333-031',
                'alamat' => 'jl vetran',
                'nisn' => '65706087',
                'id_kelas' => 8,
                'id_spp' => 2,
                'no_telp' => '65708736753',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Abraham Scott Tangguh Bida',
                'nis' => '333-032',
                'alamat' => 'jl pajayang',
                'nisn' => '67561841',
                'id_kelas' => 8,
                'id_spp' => 2,
                'no_telp' => '67584136777',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Achtor Teratai Sebatanan',
                'nis' => '333-033',
                'alamat' => 'jl pajayang',
                'nisn' => '63227092',
                'id_kelas' => 8,
                'id_spp' => 2,
                'no_telp' => '63209236799',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Aldiksa Ilyas Agustian',
                'nis' => '333-034',
                'alamat' => 'jl poros maros-makassar',
                'nisn' => '71693377',
                'id_kelas' => 8,
                'id_spp' => 2,
                'no_telp' => '71637736657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Andi Ghefira Dwi Azahra',
                'nis' => '333-035',
                'alamat' => 'jl pajayang',
                'nisn' => '61777053',
                'id_kelas' => 8,
                'id_spp' => 2,
                'no_telp' => '61755336657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Ayu Wardana',
                'nis' => '333-036',
                'alamat' => 'btn kodam',
                'nisn' => '65119233',
                'id_kelas' => 8,
                'id_spp' => 2,
                'no_telp' => '65123336657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Chelsea Fatima Al-Zahra Panjaitan',
                'nis' => '333-037',
                'alamat' => 'btn kodam',
                'nisn' => '66242936',
                'id_kelas' => 8,
                'id_spp' => 2,
                'no_telp' => '662936366',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Dewi Wulandari Zainuddin',
                'nis' => '333-038',
                'alamat' => 'jl sudiang raya',
                'nisn' => '65207271',
                'id_kelas' => 8,
                'id_spp' => 2,
                'no_telp' => '65227136657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Diszhar Aysar Hasnur',
                'nis' => '333-039',
                'alamat' => 'jl mamuju',
                'nisn' => '79856361',
                'id_kelas' => 8,
                'id_spp' => 2,
                'no_telp' => '79836188657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Dwi Puspita Sari',
                'nis' => '333-040',
                'alamat' => 'jl mamuju',
                'nisn' => '73397341',
                'id_kelas' => 8,
                'id_spp' => 2,
                'no_telp' => '733341776657',
                'jenis_kelamin' => 'p',
            ],
        ],
        'XII RPL 1' => [
            [
                'nama' => 'Ahmad Ramadhan',
                'nis' => '444-001',
                'alamat' => 'jl pajayang',
                'nisn' => '67431916',
                'id_kelas' => 9,
                'id_spp' => 3,
                'no_telp' => '8966674536753',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Alfathino Ramadhan',
                'nis' => '444-002',
                'alamat' => 'jl goaria',
                'nisn' => '65432049',
                'id_kelas' => 9,
                'id_spp' => 3,
                'no_telp' => '8966674536777',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Alifiah Ramadhani',
                'nis' => '444-003',
                'alamat' => 'jl dg rammang',
                'nisn' => '63433508',
                'id_kelas' => 9,
                'id_spp' => 3,
                'no_telp' => '8966674536799',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Anam Surya Dafi',
                'nis' => '444-004',
                'alamat' => 'jl printis km 08',
                'nisn' => '78434422',
                'id_kelas' => 9,
                'id_spp' => 3,
                'no_telp' => '8966674536657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Andi Imran Pratama',
                'nis' => '444-005',
                'alamat' => 'jl mamuju',
                'nisn' => '78439594',
                'id_kelas' => 9,
                'id_spp' => 3,
                'no_telp' => '8966684536657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Nadila Nur Azizah',
                'nis' => '444-006',
                'alamat' => 'btn kondam',
                'nisn' => '63436686',
                'id_kelas' => 9,
                'id_spp' => 3,
                'no_telp' => '8966684536657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Nilang Cahya',
                'nis' => '444-007',
                'alamat' => 'jl pettarani',
                'nisn' => '63437996',
                'id_kelas' => 9,
                'id_spp' => 3,
                'no_telp' => '8966684536657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Nur Afni Aprilia',
                'nis' => '444-008',
                'alamat' => 'jl sudiang raya',
                'nisn' => '63430033',
                'id_kelas' => 9,
                'id_spp' => 3,
                'no_telp' => '8966684536657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Nur Bungasari .J',
                'nis' => '444-009',
                'alamat' => 'jl manikoaya',
                'nisn' => '63434972',
                'id_kelas' => 9,
                'id_spp' => 3,
                'no_telp' => '8966684588657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Nurhikmah',
                'nis' => '444-010',
                'alamat' => 'bps 1 blk f8 no 19',
                'nisn' => '634339444',
                'id_kelas' => 9,
                'id_spp' => 3,
                'no_telp' => '89666847776657',
                'jenis_kelamin' => 'p',
            ],
        ],
        'XII RPL 2' => [
            [
                'nama' => 'Ahmad Imam Fahresi',
                'nis' => '444-011',
                'alamat' => 'jl vetran',
                'nisn' => '62165592',
                'id_kelas' => 10,
                'id_spp' => 3,
                'no_telp' => '6339609236753',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Ahmad Zahid Syarifuddin',
                'nis' => '444-012',
                'alamat' => 'jl pajayang',
                'nisn' => '65805526',
                'id_kelas' => 10,
                'id_spp' => 3,
                'no_telp' => '6337812636777',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Alfiano Egot',
                'nis' => '444-013',
                'alamat' => 'jl pajayang',
                'nisn' => '69185549',
                'id_kelas' => 10,
                'id_spp' => 3,
                'no_telp' => '6338574936799',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Andi Fachrie Rachman',
                'nis' => '444-014',
                'alamat' => 'jl poros maros-makassar',
                'nisn' => '73675505',
                'id_kelas' => 10,
                'id_spp' => 3,
                'no_telp' => '7332920536657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Andi Nurul Uswa Baso',
                'nis' => '444-015',
                'alamat' => 'jl pajayang',
                'nisn' => '79555534',
                'id_kelas' => 10,
                'id_spp' => 3,
                'no_telp' => '7332523436657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Azmi Nur Syaifa',
                'nis' => '444-016',
                'alamat' => 'btn kodam',
                'nisn' => '73675516',
                'id_kelas' => 10,
                'id_spp' => 3,
                'no_telp' => '7332041636657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Fifi Muliani',
                'nis' => '444-017',
                'alamat' => 'btn kodam',
                'nisn' => '61855511',
                'id_kelas' => 10,
                'id_spp' => 3,
                'no_telp' => '6335981136657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Firmansyah',
                'nis' => '444-018',
                'alamat' => 'jl sudiang raya',
                'nisn' => '58245536',
                'id_kelas' => 10,
                'id_spp' => 3,
                'no_telp' => '5338883636657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Ikmal Khair Wirawan',
                'nis' => '444-019',
                'alamat' => 'jl mamuju',
                'nisn' => '68295524',
                'id_kelas' => 10,
                'id_spp' => 3,
                'no_telp' => '6338132488657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Isra',
                'nis' => '444-020',
                'alamat' => 'jl mamuju',
                'nisn' => '72765551',
                'id_kelas' => 10,
                'id_spp' => 3,
                'no_telp' => '73333751776657',
                'jenis_kelamin' => 'l',
            ],
        ],
        'XII TKJ 1' => [
            [
                'nama' => 'Agus Andhani Purwadi',
                'nis' => '444-021',
                'alamat' => 'jl vetran',
                'nisn' => '6158881',
                'id_kelas' => 11,
                'id_spp' => 3,
                'no_telp' => '7727878765753',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Airin Putri Wulandari',
                'nis' => '444-022',
                'alamat' => 'jl pajayang',
                'nisn' => '7358887',
                'id_kelas' => 11,
                'id_spp' => 3,
                'no_telp' => '7712683765777',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Amirul Ihsan',
                'nis' => '444-023',
                'alamat' => 'jl pajayang',
                'nisn' => '7658881',
                'id_kelas' => 11,
                'id_spp' => 3,
                'no_telp' => '7714128765799',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Andi Rexa Destalia',
                'nis' => '444-024',
                'alamat' => 'jl poros maros-makassar',
                'nisn' => '6858884',
                'id_kelas' => 11,
                'id_spp' => 3,
                'no_telp' => '7732119765657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Arya Saputra',
                'nis' => '444-025',
                'alamat' => 'jl pajayang',
                'nisn' => '6758889',
                'id_kelas' => 11,
                'id_spp' => 3,
                'no_telp' => '7730179765657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Azizah Putri Nurmaidah',
                'nis' => '444-026',
                'alamat' => 'btn kodam',
                'nisn' => '7458887',
                'id_kelas' => 11,
                'id_spp' => 3,
                'no_telp' => '7781561765657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Bayu Nurhuda',
                'nis' => '444-027',
                'alamat' => 'btn kodam',
                'nisn' => '305888284',
                'id_kelas' => 11,
                'id_spp' => 3,
                'no_telp' => '7768020765366',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Boney Marshel Latupeirissa',
                'nis' => '444-028',
                'alamat' => 'jl sudiang raya',
                'nisn' => '7358882',
                'id_kelas' => 11,
                'id_spp' => 3,
                'no_telp' => '7726465765657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Elsa Sulian',
                'nis' => '444-029',
                'alamat' => 'jl mamuju',
                'nisn' => '6858885',
                'id_kelas' => 11,
                'id_spp' => 3,
                'no_telp' => '7799327765657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Khairun Nisa',
                'nis' => '444-030',
                'alamat' => 'jl mamuju',
                'nisn' => '7958883',
                'id_kelas' => 11,
                'id_spp' => 3,
                'no_telp' => '77700727656657',
                'jenis_kelamin' => 'p',
            ],
        ],
        'XII MMK 1' => [
            [
                'nama' => 'Abil Ardhaya Simanungkalit',
                'nis' => '444-031',
                'alamat' => 'jl vetran',
                'nisn' => '65886087',
                'id_kelas' => 12,
                'id_spp' => 3,
                'no_telp' => '00708736753',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Abraham Scott Tangguh Bida',
                'nis' => '444-032',
                'alamat' => 'jl pajayang',
                'nisn' => '67881841',
                'id_kelas' => 12,
                'id_spp' => 3,
                'no_telp' => '00584136777',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Achtor Teratai Sebatanan',
                'nis' => '444-033',
                'alamat' => 'jl pajayang',
                'nisn' => '63887092',
                'id_kelas' => 12,
                'id_spp' => 3,
                'no_telp' => '00209236799',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Aldiksa Ilyas Agustian',
                'nis' => '444-034',
                'alamat' => 'jl poros maros-makassar',
                'nisn' => '71883377',
                'id_kelas' => 12,
                'id_spp' => 3,
                'no_telp' => '00637736657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Andi Ghefira Dwi Azahra',
                'nis' => '444-035',
                'alamat' => 'jl pajayang',
                'nisn' => '61887553',
                'id_kelas' => 12,
                'id_spp' => 3,
                'no_telp' => '00755336657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Ayu Wardana',
                'nis' => '444-036',
                'alamat' => 'btn kodam',
                'nisn' => '65889233',
                'id_kelas' => 12,
                'id_spp' => 3,
                'no_telp' => '00123336657',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Chelsea Fatima Al-Zahra Panjaitan',
                'nis' => '444-037',
                'alamat' => 'btn kodam',
                'nisn' => '66882936',
                'id_kelas' => 12,
                'id_spp' => 3,
                'no_telp' => '002936366',
                'jenis_kelamin' => 'p',
            ],
            [
                'nama' => 'Dewi Wulandari Zainuddin',
                'nis' => '444-038',
                'alamat' => 'jl sudiang raya',
                'nisn' => '65887271',
                'id_kelas' => 12,
                'id_spp' => 3,
                'no_telp' => '00227136657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Diszhar Aysar Hasnur',
                'nis' => '444-039',
                'alamat' => 'jl mamuju',
                'nisn' => '79886361',
                'id_kelas' => 12,
                'id_spp' => 3,
                'no_telp' => '00836188657',
                'jenis_kelamin' => 'l',
            ],
            [
                'nama' => 'Dwi Puspita Sari',
                'nis' => '444-040',
                'alamat' => 'jl mamuju',
                'nisn' => '73887341',
                'id_kelas' => 12,
                'id_spp' => 3,
                'no_telp' => '003341776657',
                'jenis_kelamin' => 'p',
            ],
        ],
    ]
];



    $data_spp = [
        [
            "level" => 'X',
            "nominal" => 170000,
        ],
        [
            "level" => 'XI',
            "nominal" => 200000,
        ],
        [
            "level" => 'XII',
            "nominal" => 250000,
        ],
    ];



    $data_kelas = [
        [
            "nama_kelas" => "X RPL 1",
            "kompetensi_keahlian" => "Rekayasa Prangkat Lunak",
        ],
        [
            "nama_kelas" => "X RPL 2",
            "kompetensi_keahlian" => "Rekayasa Prangkat Lunak",
        ],
        [
            "nama_kelas" => "X TKJ 1",
            "kompetensi_keahlian" => "Teknik Komputer Jaringan",
        ],
        [
            "nama_kelas" => "X MMK 1",
            "kompetensi_keahlian" => "Multi Media",
        ],
        [
            "nama_kelas" => "XI RPL 1",
            "kompetensi_keahlian" => "Rekayasa Prangkat Lunak",
        ],
        [
            "nama_kelas" => "XI RPL 2",
            "kompetensi_keahlian" => "Rekayasa Prangkat Lunak",
        ],
        [
            "nama_kelas" => "XI TKJ 1",
            "kompetensi_keahlian" => "Teknik Komputer Jaringan",
        ],
        [
            "nama_kelas" => "XI MMK 1",
            "kompetensi_keahlian" => "Multi Media",
        ],
        [
            "nama_kelas" => "XII RPL 1",
            "kompetensi_keahlian" => "Rekayasa Prangkat Lunak",
        ],
        [
            "nama_kelas" => "XII RPL 2",
            "kompetensi_keahlian" => "Rekayasa Prangkat Lunak",
        ],
        [
            "nama_kelas" => "XII TKJ 1",
            "kompetensi_keahlian" => "Teknik Komputer Jaringan",
        ],
        [
            "nama_kelas" => "XII MMK 1",
            "kompetensi_keahlian" => "Multi Media",
        ],
    ];

    //! SEEDER DATA SPP
    $data_spp = [
        [
            "level" => 'X',
            "nominal" => 170000,
        ],
        [
            "level" => 'XI',
            "nominal" => 200000,
        ],
        [
            "level" => 'XII',
            "nominal" => 250000,
        ],
    ];


foreach ($petugas as $user) {
    User::create($user);
}
foreach ($siswass as $siswas) {
    foreach ($siswas as $siswa) {
        foreach ($siswa as $s) {
            Siswa::create($s);
        }
    }
}
// Siswa::factory()->count(10)->create();
// User::factory()->count(10)->create();
// // foreach ($pembayaran as $bayar) {
// //     Pembayaran::create($bayar);
// // }
foreach ($data_spp as $spp) {
    Spp::create($spp);
}
foreach ($data_kelas as $kelas) {
    Kelas::create($kelas);
}

    }


}
